const root=document.documentElement;const langBtn=document.getElementById('lang');
langBtn?.addEventListener('click',()=>{const ar=root.lang!=='ar';root.lang=ar?'ar':'en';root.dir=ar?'rtl':'ltr';document.body.classList.toggle('ar',ar);document.querySelectorAll('[data-en]').forEach(el=>el.textContent=ar?el.dataset.ar:el.dataset.en);document.querySelectorAll('[data-ph-en]').forEach(el=>el.placeholder=ar?el.dataset.phAr:el.dataset.phEn);langBtn.textContent=ar?'EN':'AR';});
const heroVideos=[...document.querySelectorAll('.hero-video')];
const heroSources=['https://videos.pexels.com/video-files/4000033/4000033-hd_1920_1080_25fps.mp4','https://videos.pexels.com/video-files/6194507/6194507-hd_1920_1080_25fps.mp4'];
heroVideos.forEach((video,i)=>{const source=video.querySelector('source');if(source&&heroSources[i]){source.src=heroSources[i];video.load();video.play().catch(()=>{});}});
const reveals=document.querySelectorAll('.reveal');const revealObs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revealObs.unobserve(e.target)}}),{threshold:.12});reveals.forEach(el=>revealObs.observe(el));
let active=0;if(heroVideos.length>1){setInterval(()=>{heroVideos[active].classList.remove('active');active=(active+1)%heroVideos.length;heroVideos[active].classList.add('active')},7000)}
const glow=document.querySelector('.cursor-glow');window.addEventListener('pointermove',e=>{if(glow){glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'}});
document.querySelectorAll('.filters button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filters button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;document.querySelectorAll('.equipment-card').forEach(card=>card.classList.toggle('hide',f!=='all'&&card.dataset.cat!==f));}));
document.querySelectorAll('.equipment-card').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(800px) rotateX(${y*-5}deg) rotateY(${x*6}deg) translateY(-8px)`});card.addEventListener('pointerleave',()=>card.style.transform='')});
window.addEventListener('scroll',()=>{const y=window.scrollY;document.querySelectorAll('.hero-video').forEach(v=>v.style.transform=`scale(${1.02+y*.00003}) translateY(${y*.08}px)`);});